---
- name: check if firewalld is installed (on redhat)
  yum:
    list: firewalld
  register: firewall_installed

- name: disable the firewalld service (on rhel, if configured)
  service:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - firewall_disable_firewalld
    - firewall_installed.results | selectattr("yumstate", "match", "installed")|list|length > 0

- name: install iptables centos 6
  yum:
    name: iptables
  when: ansible_distribution_major_version|int == 6

- name: install iptables centos 7
  yum:
    name:
      - iptables
      - iptables-services
  when: ansible_distribution_major_version|int == 7

- name: enable firewall on boot
  service:
    name: iptables
    enabled: "{{ firewall_enable_on_boot }}"
