# vim: ai et ts=2 st=2 sw=2 :
---
- name: install dependencies centos 7
  yum:
    name:
      - libselinux-python
      - yum-utils
  when: ansible_distribution_major_version|int == 7
  check_mode: false

- name: install dependencies centos 8
  dnf:
    name:
      - python3-libselinux
      - dnf-utils
  when: ansible_distribution_major_version|int == 8
  check_mode: false

- name: check if firewalld is installed (on redhat)
  yum:
    list: firewalld
  register: firewall_installed

- name: disable the firewalld service (on rhel, if configured)
  service:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - not ansible_check_mode
    - firewall_disable_firewalld
    - firewall_installed.results | selectattr("yumstate", "match", "installed")|list|length > 0

- name: install iptables centos 7
  yum:
    name:
      - iptables
      - iptables-services
  when: ansible_distribution_major_version|int == 7

- name: install iptables centos 8
  dnf:
    name:
      - iptables
      - iptables-services
  when: ansible_distribution_major_version|int == 8

- name: enable firewall on boot
  service:
    name: iptables
    enabled: "{{ firewall_enable_on_boot }}"

- name: iptables templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/sysconfig/{{ item }}"
    owner: root
    group: root
    mode: 0600
    validate: bash -c 'cat %s | /sbin/{{ item }}-restore --test'
  loop:
    - iptables
    - ip6tables
  register: iptables_templates
  when:
    - not is_docker
    - not firewall_is_neutron

- name: iptables templates for docker hosts
  template:
    src: "{{ item }}.j2-docker"
    dest: "/etc/sysconfig/{{ item }}"
    owner: root
    group: root
    mode: 0600
    validate: bash -c 'cat %s | /sbin/{{ item }}-restore --test'
  loop:
    - iptables
    - ip6tables
  register: iptables_templates_docker
  when: is_docker

- name: iptables templates for neutron hosts
  template:
    src: "{{ item }}.j2-neutron"
    dest: "/etc/sysconfig/{{ item }}"
    owner: root
    group: root
    mode: 0600
    validate: bash -c 'cat %s | /sbin/{{ item }}-restore --test'
  loop:
    - iptables
    - ip6tables
  register: iptables_templates_neutron
  when: firewall_is_neutron

- name: create ipsets
  include: "ipset.yml"
  when: firewall_ipset

- name: load new rules
  shell: "set -o pipefail && cat /etc/sysconfig/{{ item }} | {{ item }}-restore --noflush"
  args:
    executable: bash
  loop:
    - iptables
    - ip6tables
  when:
    - iptables_templates is changed or iptables_templates_docker is changed or iptables_templates_neutron is changed
    - not firewall_flush_on_change
    - not is_neutron_loaded

- name: load new rules when neutron is loaded
  shell: "set -o pipefail && cat /etc/sysconfig/{{ item }} | sed 's/^:neutron.*$//g' | {{ item }}-restore --noflush"
  args:
    executable: bash
  loop:
    - iptables
    - ip6tables
  when:
    - iptables_templates_neutron is changed
    - not firewall_flush_on_change
    - is_neutron_loaded

- name: restart iptables
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - iptables
    - ip6tables
  when:
    - iptables_templates is changed or iptables_templates_docker is changed or iptables_templates_neutron is changed
    - firewall_flush_on_change
